Workshop HoGent/force-app/main/default/objects/Paper__c/Paper__c.object-meta.xml
<CustomObject>
    <label>Paper</label>
    <nameField>
        <label>Paper Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paper</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Workshop HoGent/force-app/main/default/objects/Paper__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>White,</fullName>
                <default>true</default>
                <label>White,</label>
            </value>
            <value>
                <fullName>Red,</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Blue,</fullName>
            </value>
            <value>
                <fullName>Orange,</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Workshop HoGent/force-app/main/default/objects/Paper__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A1</fullName>
            </value>
            <value>
                <fullName>A2</fullName>
            </value>
            <value>
                <fullName>A3</fullName>
            </value>
            <value>
                <fullName>A4</fullName>
            </value>
            <value>
                <fullName>A5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Workshop HoGent/force-app/main/default/classes/managers/PaperManager.cls
public with sharing class PaperManager {

    private List<Paper__c> recordList = new List<Paper__c>();
    private Map<Id, Paper__c> oldValueMap = new Map<Id, Paper__c>();

    public PaperManager(List<Paper__c> recordList) {
        this.recordList = recordList;
        setPaperNameField();
    }
    
    public PaperManager(List<Paper__c> recordList, Map<Id, Paper__c> oldValueMap) {
        this(recordList);
        this.oldValueMap = oldValueMap;
    }


    private void setPaperNameField() {
        for (Paper__c paper: recordList) {
            string name = paper.name + ' | ' + paper.size__c + ' | ' + paper.color__c;
            paper.Name = name;
        }
    }
}